### ISSUE TITLE
The active note has white background instead of orange

### ISSUE THREAD

**Issue by ancientPrinter** [ceiphr/sn-yaru-theme#2]
This is on the web version.

Screenshot: https://imgur.com/a/MEt3UIN

Great theme by the way. Thanks for creating it!

**Comment by ceiphr** [comment]
Thank you for bringing this to my attention, and thank you for the complement!

I'll have this sorted out by tonight.

**Comment by ceiphr** [comment]
This should be fixed in the latest release.

Please reopen if the issue persists. Thank you!
